//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W3KlinikKami.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AKUN
    {
        public int ID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD_AKUN { get; set; }
    
        public virtual TB_USER TB_USER { get; set; }
    }
}
