//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W3KlinikKami.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_KUNJUNGAN_PASIEN
    {
        public System.DateTime TANGGAL_KUNJUNGAN { get; set; }
        public int ID_PASIEN { get; set; }
        public Nullable<bool> STATUS_PENANGANAN { get; set; }
        public string KETERANGAN { get; set; }
    
        public virtual TB_PASIEN TB_PASIEN { get; set; }
    }
}
