//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W3KlinikKami.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_KUNJUNGAN_PASIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_KUNJUNGAN_PASIEN()
        {
            this.TB_DATA_PENANGANAN_PASIEN = new HashSet<TB_DATA_PENANGANAN_PASIEN>();
        }
    
        public int ID { get; set; }
        public System.DateTime TANGGAL_KUNJUNGAN { get; set; }
        public int ID_PASIEN { get; set; }
        public Nullable<bool> PENANGANAN_DOKTER { get; set; }
        public string KETERANGAN { get; set; }
        public Nullable<bool> PENGAMBILAN_OBAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DATA_PENANGANAN_PASIEN> TB_DATA_PENANGANAN_PASIEN { get; set; }
        public virtual TB_PASIEN TB_PASIEN { get; set; }
    }
}
