//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W3KlinikKami.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PASIEN
    {
        public int ID { get; set; }
        public string NAMA { get; set; }
        public string JENIS_KELAMIN { get; set; }
        public System.DateTime TANGGAL_LAHIR { get; set; }
        public string GOLONGAN_DARAH { get; set; }
        public decimal NO_HP { get; set; }
        public string ALAMAT { get; set; }
        public System.DateTime TERDAFTAR { get; set; }
    }
}
