//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W3KlinikKami.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_USER()
        {
            this.TB_DATA_PENANGANAN_PASIEN = new HashSet<TB_DATA_PENANGANAN_PASIEN>();
        }
    
        public int ID { get; set; }
        public string NAMA { get; set; }
        public string JENIS_KELAMIN { get; set; }
        public decimal NO_HP { get; set; }
        public string ALAMAT { get; set; }
        public string FOTO { get; set; }
        public string JABATAN { get; set; }
        public System.DateTime TERDAFTAR { get; set; }
    
        public virtual TB_AKUN TB_AKUN { get; set; }
        public virtual TB_JABATAN TB_JABATAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DATA_PENANGANAN_PASIEN> TB_DATA_PENANGANAN_PASIEN { get; set; }
    }
}
